### ISSUE TITLE
.step file parsing error

### ISSUE THREAD

**Issue by pbradylogitech** [mozman/steputils#1]
I am unable to read a step file.
These .step file are coming from Rhino & Creo professional tools
I keep getting the following error.

```
File "D:\Progam Files\Python\python v3.7.0\lib\site-packages\steputils\p21.py", line 1025, in readfile
    return load(fp)
  File "D:\Progam Files\Python\python v3.7.0\lib\site-packages\steputils\p21.py", line 1019, in load
    return loads(content)
  File "D:\Progam Files\Python\python v3.7.0\lib\site-packages\steputils\p21.py", line 1003, in loads
    return Parser(lexer).parse()
  File "D:\Progam Files\Python\python v3.7.0\lib\site-packages\steputils\p21.py", line 633, in __init__
    self.tokens = list(lexer.parse())
  File "D:\Progam Files\Python\python v3.7.0\lib\site-packages\steputils\p21.py", line 505, in parse
    yield step_decoder(self.string())  # str
  File "D:\Progam Files\Python\python v3.7.0\lib\site-packages\steputils\p21.py", line 557, in string
    raise ParseError(f'Found invalid character in string "{current}".')
steputils.exceptions.ParseError: Found invalid character in string "
".
```

When I open the .stp files in notepad++ text editor, the encoding is UTF-8. 
I tried changing the file encoding to ISO 8859-1 without any success.

**Comment by alex89607** [comment]
Suppose, the same error, when I am tring to import fie with one line(exported from [FreeCad/]
Found invalid character in string "
".


`ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('FreeCAD Model'),'2;1');
FILE_NAME(
'/media/alexandr/ftl/-curr/con- 
isometric-orthogonal-projections/orthogonal/3workfolder/test2.step',
  '2020-09-03T01:28:01',('Author'),(''),
  'Open CASCADE STEP processor 7.3','FreeCAD','Unknown');
FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));
ENDSEC;
DATA;
#1 = APPLICATION_PROTOCOL_DEFINITION('international standard',
  'automotive_design',2000,#2);
#2 = APPLICATION_CONTEXT(
  'core data for automotive mechanical design processes');
#3 = SHAPE_DEFINITION_REPRESENTATION(#4,#10);
#4 = PRODUCT_DEFINITION_SHAPE('','',#5);
#5 = PRODUCT_DEFINITION('design','',#6,#9);
#6 = PRODUCT_DEFINITION_FORMATION('','',#7);
#7 = PRODUCT('Shape','Shape','',(#8));
#8 = PRODUCT_CONTEXT('',#2,'mechanical');
#9 = PRODUCT_DEFINITION_CONTEXT('part definition',#2,'design');
#10 = GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION('',(#11,#15),
  #23);
#11 = AXIS2_PLACEMENT_3D('',#12,#13,#14);
#12 = CARTESIAN_POINT('',(0.,0.,0.));
#13 = DIRECTION('',(0.,0.,1.));
#14 = DIRECTION('',(1.,0.,-0.));
#15 = GEOMETRIC_CURVE_SET('',(#16));
#16 = TRIMMED_CURVE('',#17,(#21,PARAMETER_VALUE(0.)),(#22,
    PARAMETER_VALUE(54.)),.T.,.PARAMETER.);
#17 = LINE('',#18,#19);
#18 = CARTESIAN_POINT('',(4.174E+03,381.,0.));
#19 = VECTOR('',#20,1.);
#20 = DIRECTION('',(-1.,0.,0.));
#21 = CARTESIAN_POINT('',(4.174E+03,381.,0.));
#22 = CARTESIAN_POINT('',(4.12E+03,381.,0.));
#23 = ( GEOMETRIC_REPRESENTATION_CONTEXT(3) 
GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT((#27)) GLOBAL_UNIT_ASSIGNED_CONTEXT(
(#24,#25,#26)) REPRESENTATION_CONTEXT('Context #1',
  '3D Context with UNIT and UNCERTAINTY') );
#24 = ( LENGTH_UNIT() NAMED_UNIT(*) SI_UNIT(.MILLI.,.METRE.) );
#25 = ( NAMED_UNIT(*) PLANE_ANGLE_UNIT() SI_UNIT($,.RADIAN.) );
#26 = ( NAMED_UNIT(*) SI_UNIT($,.STERADIAN.) SOLID_ANGLE_UNIT() );
#27 = UNCERTAINTY_MEASURE_WITH_UNIT(LENGTH_MEASURE(1.E-07),#24,
  'distance_accuracy_value','confusion accuracy');
#28 = PRODUCT_RELATED_PRODUCT_CATEGORY('part',$,(#7));
#29 = MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION('',(#30),
  #23);
#30 = STYLED_ITEM('color',(#31),#15);
#31 = PRESENTATION_STYLE_ASSIGNMENT((#32,#38));
#32 = SURFACE_STYLE_USAGE(.BOTH.,#33);
#33 = SURFACE_SIDE_STYLE('',(#34));
#34 = SURFACE_STYLE_FILL_AREA(#35);
#35 = FILL_AREA_STYLE('',(#36));
#36 = FILL_AREA_STYLE_COLOUR('',#37);
#37 = COLOUR_RGB('',0.800000011921,0.800000011921,0.800000011921);
#38 = CURVE_STYLE('',#39,POSITIVE_LENGTH_MEASURE(0.1),#37);
#39 = DRAUGHTING_PRE_DEFINED_CURVE_FONT('continuous');
ENDSEC;
END-ISO-10303-21;`

**Comment by defaltus** [comment]
Importing manually and removing `\n` from the input string works for me, e.g. (suppose you have the file `test.stp` from CAD):
```python
from steputils import p21

file = open('test.stp', 'r')
input_string = file.read()
step_file = p21.loads(input_string.replace('\n', '')
```

**Comment by shinigami36** [comment]
Hi can you guys tell me how can i parse the step file and get the dimensions for the axis . Thankyou in advance
