### ISSUE TITLE
preprocessor_version should not be a tuple

### ISSUE THREAD

**Issue by hemanti0503** [mozman/steputils#7]
The method steputils.p21.HeaderSection.set_file_name assumes the parameter `preprocessor_version` to be a tuple. This seems incorrect according to the examples on [Wikipedia ](https://en.wikipedia.org/wiki/ISO_10303-21#ISO_10303-21_Building_blocks)and in the [Usage Guide for the STEP PDM Schema](https://www.cax-if.org/documents/pdmug_release4_3.pdf) (e.g. page 21 --> page 31 of PDF).

Instead, the `author` field looks like it should be a tuple.

**Comment by mozman** [comment]
This is correct and will be fixed:

```
EXPRESS Specification:

*)
ENTITY file_name;
  name                 : STRING (256) ;
  time_stamp           : time_stamp_text ;
  author               : LIST [ 1 : ? ] OF STRING (256) ;
  organization         : LIST [ 1 : ? ] OF STRING (256) ;
  preprocessor_version : STRING (256) ;
  originating_system   : STRING (256) ;
  authorization        : STRING (256) ;
END_ENTITY;

 
TYPE time_stamp_text = STRING(256);
END_TYPE;
(*
```

**Comment by hemanti0503** [comment]
I don't know much about these things, whether it's an automated process, if it's something that's quite involved, etc. So I want to ask, when I can expect the fixed version on PyPi?
